#!/var/lang/node12/bin/node

/*
# HTTP 直通函数由于是基于 docker 镜像运行，所以必须监听地址为 0.0.0.0，并且端口为 9000
*/
const { nextStart } = require('next/dist/cli/next-start');
const { existsSync } = require('fs');
console.log(__dirname, existsSync('./next.config.js'), existsSync('./src/next.config.js'));
nextStart(['--port', '9000', '--hostname', '0.0.0.0']);
