component: http
name: code-game-nextjs
inputs:
  src:
    dist: ./
  faas:
    runtime: Nodejs16.17
    framework: nextjs
    name: '${name}'
    eip: false
    timeout: 3
    memorySize: 512
    tags: []
    environments: []
    layers:
      - name: '${output:${stage}:${app}:code-game-layer.name}'
        version: '${output:${stage}:${app}:code-game-layer.version}'
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  region: ap-guangzhou
  isAutoCiDeploy: false
org: '1253213981'
app: code-game
stage: dev
