app: code-game-next
stage: dev
component: nextjs
name: code-game-next

inputs:
  src: ./
  region: ap-guangzhou
  functionConf:
    name: ${name}
    runtime: Nodejs12.16
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
  staticConf:
    cosConf:
      replace: true
      bucket: code-game-nextjs