component: nextjs
name: code-game-next
inputs:
  src:
    src: ./sls
  functionName: nextjsDemo
  region: ap-guangzhou
  runtime: Nodejs12.16
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
app: code-game
