component: http
name: code-game-ebg1FKdaHx
inputs:
  src:
    dist: ./
  faas:
    runtime: Nodejs16.13
    framework: nextjs
    name: '${name}'
    eip: false
    timeout: 3
    memorySize: 512
    tags: []
    environments:
      - key: STATIC_URL
        value: >-
          https://sls-layer-ap-guangzhou-code-1253213981.cos.ap-guangzhou.myqcloud.com
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  region: ap-guangzhou
  isAutoCiDeploy: false
  assets:
    cos:
      bucket: sls-layer-ap-guangzhou-code-1253213981
      acl:
        permissions: public-read
org: '1253213981'
app: code-game
stage: dev