app: code-game
stage: dev
component: nextjs
name: code-game-nextjs

inputs:
  src:
    dist: ./
    hook: npm run build
    exclude:
      - .env
  region: ap-guangzhou
  functionConf:
    name: ${name}
    runtime: Nodejs16.17
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
  staticConf:
    cosConf:
      replace: true
      bucket: code-game-nextjs