component: http
name: code-game
inputs:
  src:
    src: ./
    exclude:
      - node_modules
      - .github
      - .husky
      - commitlint.config.js
      - jest.config.ts
      - next-env.d.ts
      - tsconfig.json
      - tsconfig.test.json
      - tailwind.config.js
      - setupTests.ts
      - postcss.config.js
      - .eslintrc.json
      - .env
      - gitignore
  faas:
    runtime: Nodejs16.13
    framework: nextjs
    name: '${name}'
    eip: false
    timeout: 3
    memorySize: 512
    tags: []
    environments:
      - key: STATIC_URL
        value: >-
          https://sls-layer-ap-guangzhou-code-1253213981.cos.ap-guangzhou.myqcloud.com
    layers:
      - name: '${output:${stage}:${app}:code-game-layer.name}'
        version: '${output:${stage}:${app}:code-game-layer.version}'
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  region: ap-guangzhou
  isAutoCiDeploy: false
  assets:
    cos:
      bucket: sls-layer-ap-guangzhou-code-1253213981
      acl:
        permissions: public-read
org: '1253213981'
app: code-game
stage: dev