import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const DynamicHeader = dynamic(() => import('../canvas'), {
  ssr: false,
});

const Main: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DynamicHeader />
    </>
  );
};

export default Main;
