import type { NextPage } from 'next';
import Head from 'next/head';

const Main: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>登录界面</div>
      </main>
    </>
  );
};

export default Main;
