on: push
jobs:
  main:
    name: deploy serverless
    runs-on: ubuntu-latest
    steps:
      - name: clone local repository
        uses: actions/checkout@v2
      - name: install pnpm
        run: npm install -g pnpm
      - name: install dependency
        run: pnpm install
      - name: build
        run: npm run build
      - name: clean deploy
        run: find * | grep -v '\(.next\|next.config.js\|package-serverless.json\|serverless.yml\|scf_bootstrap\|layer\)' | xargs rm -rf
      - name: prepare deploy
        run: mv package-serverless.json package.json && npm i 
      - name: deploy serverless
        uses: woodyyan/tencent-serverless-action@main
        env:
          STAGE: dev
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}